server:
  port:3010
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: baidu_route
        uri: http://www.baidu.com
        predicates:
        - Path: /